enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":app")
include(":styleguide")
include(":commons-test")
include(":feature:movie-list")
include(":feature:movie-detail:public")
include(":feature:movie-detail:impl")
include(":infra:api-caller")
include(":infra:network:public")
include(":infra:network:impl")
include(":infra:action-dispatcher")
include(":design-system:view-state")
include(":design-system:illustration")
include(":design-system:tokens")
include("infra:router:public")
include("infra:router:impl")
include("infra:bundle-key")
